name: "Setup Developer Jule Compiler"
description: "Setup Developer Jule Compiler for the Official CI actions."
author: "mertcandav"
branding:
  icon: code
  color: gray-dark
runs:
  using: "composite"
  steps:
    - name: Get IR
      shell: bash
      run: |
        if [[ "$OSTYPE" == "darwin"* ]]; then
          curl -o ir.cpp https://raw.githubusercontent.com/julelang/julec-ir/main/src/darwin-amd64.cpp
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          curl -o ir.cpp https://raw.githubusercontent.com/julelang/julec-ir/main/src/windows-amd64.cpp
        elif [[ "$RUNNER_OS" == "Linux" ]]; then
          curl -o ir.cpp https://raw.githubusercontent.com/julelang/julec-ir/main/src/linux-amd64.cpp
        else
          echo "Unsupported operating system."
          exit 1
        fi
    - name: Build Jule Compiler
      shell: bash
      run: |
        mkdir bin
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          clang++ -Wno-everything --std=c++17 -fwrapv -ffloat-store -fno-fast-math -fno-rounding-math -ffp-contract=fast -O3 -flto=thin -fuse-ld=lld -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -o bin/julec.exe ir.cpp -lws2_32 -lshell32
        else
          clang++ -Wno-everything --std=c++17 -fwrapv -ffloat-store -fno-fast-math -fexcess-precision=standard -fno-rounding-math -ffp-contract=fast -O3 -flto=thin -DNDEBUG -fomit-frame-pointer -fno-strict-aliasing -o ./bin/julec ir.cpp
        fi
    - name: Add Compiler to the PATH
      shell: bash
      run: |
        echo "export PATH=\$PATH:./bin/" >> $GITHUB_PATH
